name: Invoked Workflow
on:
  push:
    branches:
      - main
      - master
      - sprint
      - release
    tags:
      - v*
  workflow_run:
    workflows: ["Build Label"]
    types: [completed]

jobs:
  build:
    name: Check For Build Label
    runs-on: ubuntu-latest
    # if: ${{ !github.event.workflow_run || github.event.workflow_run.build_label === "true" }}
    steps:
      - name: Placeholder
        uses: actions/github-script@v4
        script: |
          console.log(github.event.workflow_run)
