name: Assign Reviewer Labels
on:
  pull_request:
    types:
      - review_requested

jobs:
  apply_labels:
    name: Apply Labels
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.pull_request.requested_reviewers.*.login, 'R167')
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.addLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: "Database Review"
            })
            console.log('Added "Database Review" label')

