name: Rebuild Docker Image On Open Pull Requests

on:
  push:
    branches:
      - main
      - master
      - sprint
      - release

jobs:
  build_docker_images:
    name: Request Pull Requests Rebuild Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            const branch = context.ref.replace("refs/heads/", "")
            console.log(branch)
            github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              base: branch
            }).then(response => {
              console.log(response)
            })

