name: Buildable Test
on:
  push:
    branches:
      - main
      - master
      - sprint
      - release
    tags:
      - v*
  pull_request:
    types:
      - labeled
      - synchronize

jobs:
  check_for_build_label:
    runs-on: ubuntu-latest
    outputs:
      build_docker_image: ${{ steps.check_if_build_label.outputs.result }}
    steps:
      - id: check_if_build_label
        uses: actions/github-script@v4
        with:
          script: |
            console.log("ref " + context.ref)
            console.log("issue " + context.issue.number)
            if (context.ref.match(/^refs\/heads\/(main|master|sprint|release)$/) || context.ref.match(/^refs\/tags\/v/)) {
              console.log("Buildable reference " + context.ref)
              return "true"
            } else if (context.issue.number) {
              const labels = await github.issues.listLabelsOnIssue({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100
              })
              let buildLabelFound = false
              console.log(labels)
              labels.forEach((label) => {
                if (label.name === "QA Ready" || label.name === "Build Image") {
                  console.log("Buildable label " + label.name)
                  buildLabelFound = true
                  return
                }
              })
              if (buildLabelFound) {
                return "true"
              }
            }
            console.log("Docker image will not be built")
            return null
