name: Buildable Test
on:
  push:
    branches:
      - master
      - sprint
      - release
    tags:
      - v*
  pull_request:
    types:
      - labeled

concurrency: build_docker_image-${{ github.ref }}

jobs:
  check_for_build_label:
    runs-on: ubuntu-latest
    outputs:
      build_docker_image: ${{ steps.check_if_build_label.outputs.result }}
    steps:
      - id: check_if_build_label
        uses: actions/github-script@v4
        with:
          script: |
            const labels = github.issues.getLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            })
            let buildLabelFound = false
            labels.forEach(=>(label){
              if (label.name === "QA Ready" || label.name === "Build Image") {
                buildLabelFound = true
                break
              }
            })
            if (buildLabelFound) {
              return "true"
            } else {
              return "false"
            }
