name: Build Label
on:
  pull_request:
    types:
      - labeled
      - synchronize

jobs:
  check_for_build_label:
    name: Check For Build Label
    runs-on: ubuntu-latest
    outputs:
      build_label: ${{ steps.check_labels.outputs.result }}
    steps:
      - name: Check Labels
        id: check_labels
        uses: actions/github-script@v4
        with:
          script: |
            const labels = await github.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            })
            let buildLabel = null
            labels.data.forEach(label => {
              if (label.name === "QA Ready" || label.name === "Build Image") {
                buildLabel = label.name
                return
              }
            })
            if (buildLabel) {
              console.log("Build label found: " + buildLabel)
              return "true"
            } else {
              console.log("Build label not found")
              return "false"
            }
      - name: Set Workflow Output
        id: set_output
        run: |-
          ls -la
          echo "::set-output name=build_label::${{ steps.check_labels.outputs.result }}"
