name: Buildable Test
on:
  push:
    branches:
      - main
      - master
      - sprint
      - release
    tags:
      - v*
  pull_request:
    types:
      - labeled

jobs:
  check_for_build_label:
    runs-on: ubuntu-latest
    outputs:
      build_docker_image: ${{ steps.check_if_build_label.outputs.result }}
    steps:
      - id: check_if_build_label
        uses: actions/github-script@v4
        with:
          script: |
            console.log(context.ref, context.issue.number)
            if (context.issue.number) {
              let buildLabelFound = false
              github.issues.listLabelsOnIssue({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100
              }).then(labels => {
                console.log(labels)
                labels.forEach((label) => {
                  if (label.name === "QA Ready" || label.name === "Build Image") {
                    console.log("Buildable label " + label.name)
                    buildLabelFound = true
                    return
                  }
                })
              })
              if (buildLabelFound) {
                return "true"
              }
            } else {
              if (context.ref.match(/^\/refs\/head\/(main|master|sprint|release)$/) || context.ref.match(/^\/refs\/tags\/v/)) {
                console.log("Buildable reference " + context.ref)
                return "true"
              }
            }
            console.log("Docker image will not be built")
            return null
