name: Buildable Test
on:
  push:
    branches:
      - main
      - master
      - sprint
      - release
    tags:
      - v*
  pull_request:
    types:
      - labeled
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check If Buildable
        id: buildable_check
        uses: actions/github-script@v4
        with:
          script: |
            console.log(context.event)
            console.log(context.event.pull_request)
            Object.keys(context.event.pull_request.labels).forEach(lb => { console.log(label)})
            const branchMatcher = /^refs\/heads\/(main|master|sprint|release)$/
            const branchMatch = context.ref.match(branchMatcher)
            if (branchMatch) {
              console.log("Buildable branch " + branchMatch[1])
              return "branch/" + branchMatch[1]
            }
            const tagMatcher = /^refs\/tags\/v/
            const tagMatch = context.ref.match(branchMatcher)
            if (tagMatch) {
              console.log("Buildable tag " + tagMatch[1])
              return "tag/" + tagMatch[1]
            }
            const labels = await github.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            })
            let buildLabel = null
            labels.data.forEach(label => {
              if (label.name === "QA Ready" || label.name === "Build Image") {
                buildLabel = label.name
                return
              }
            })
            if (buildLabel) {
              console.log("Build label found: " + buildLabel)
              return "label/" + buildLabel
            } else {
              console.log("Build label not found")
              return null
            }
      steps:
        - name: Placeholder
          uses: actions/github-script@v4
          script: |
            echo "Placeholder"
