name: Label Database Changes For Review
on:
  pull_request:
    types:
      - synchronize
      - opened

concurrency: build_docker_image-${{ github.ref }}

jobs:
  build_docker_image:
    name: Check For Database Changes
    runs-on: ubuntu-latest
    steps:
      - name: Check for changes in db/**/* files
        uses: actions/github-script@v4
        with:
          script: |
            let page = 1
            while (true) {
              files = await github.pulls.listFiles({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                per_page: 1,
                page: page
              })
              console.log(files)
              break
            }
