name: Jira Transitions

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  build:
    if: contains(github.event.label.name, 'QA Ready')
    runs-on: ubuntu-latest
    name: Transition Jira Task From Labels
    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    steps:
      - name: Find Jira Issue
        id: find_jira_issue
        env:
          search_string: ${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.title }} ${{ github.event.pull_request.body }}
          patterns: \b(ENG)-([0-9]+)
        run: |
          issue=$(echo $search_string | grep -Eoi -e $patterns)
          if [ "$issue" != "" ]; then
            echo "::set-output name=issue::${issue}"
          fi
      - name: Get Issue Status
        if: steps.find_jira_issue.outputs.issue
        run: |
          url="${JIRA_BASE_URL}/rest/api/2/issue/${{ steps.find_jira_issue.outputs.issue }}?fields=status"
          status=$(curl -u ${JIRA_USER_EMAIL}:${JIRA_API_TOKEN} -X GET -H "Content-Type: application/json" $url)
          echo $status
          echo "::set-output name=status::${issue}"
     # - name: Transition Issue To QA Ready
     #    if: steps.find_jira_issue.outputs.issue && github.event.action == 'labeled'
     #    uses: atlassian/gajira-transition@v2.0.2
     #    with:
     #      issue: ${{ steps.find_jira_issue.outputs.issue }}
     #      transition: "QA Ready"
     #  - name: Transition Issue To In Progress
     #    if: steps.find_jira_issue.outputs.issue && github.event.action == 'unlabeled'
     #    uses: atlassian/gajira-transition@v2.0.2
     #    with:
     #      issue: ${{ steps.find_jira_issue.outputs.issue }}
     #      transition: "In Progress"
