name: Jira Transitions

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  build:
    # if: contains(github.event.label.name, 'QA Ready')
    runs-on: ubuntu-latest
    name: Transition Jira Task From Labels
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - name: Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Find Jira Issue
        id: find_jira_issue
        uses: atlassian/gajira-find-issue-key@v2.0.2
        with:
          string: ${{ github.event.head.ref }} ${{ github.event.pull_request.title }} ${{ github.event.pull_request.body }}
      - name: Transition Issue To QA Ready
        if: steps.find_jira_issue.outputs.issue && github.event.action == 'labeled'
        uses: atlassian/gajira-transition@v2.0.2
        with:
          issue: ${{ steps.find_jira_issue.outputs.issue }}
          transition: "Done"
      - name: Transition Issue To In Progress
        if: steps.find_jira_issue.outputs.issue && github.event.action == 'unlabeled'
        uses: atlassian/gajira-transition@v2.0.2
        with:
          issue: ${{ steps.find_jira_issue.outputs.issue }}
          transition: "In Progress"
