name: Label Filter
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Label
        if: contains(github.event.pull_request.labels.*.name, 'Build Image')
        run: |
          echo Has Label
      - name: Check Not Label
        if: "!contains(github.event.pull_request.labels.*.name, 'Build Image')"
        run: |
          echo No Label
