name: Label Filter
on:
  pull_request:
    types:
      - labeled
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Label
        if: contains(github.event.pull_request.labels.*.name, 'bug')
        run: |
          echo Has Label
      - name: Check Label
        if: "!contains(github.event.pull_request.labels.*.name, 'bug')"
        run: |
          echo No Label
