name: Label Filter
on:
  push:
    branches:
      - main
      - master
      - sprint
      - release
    tags:
      - v*
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check For Build Image Label
        id: check_for_build_image
        if: contains(github.event.pull_request.labels.*.name, 'Build Image')
        run: echo "::set-output name=result::true"
      - name: Check For QA Ready Label
        id: check_for_qa_ready
        if: contains(github.event.pull_request.labels.*.name, 'QA Ready')
        run: echo "::set-output name=result::true"
      - name: Buildable
        id: buildable
        if: github.event_name == 'push' || steps.check_for_build_image.outputs.result == 'true' || steps.check_for_build_image.outputs.result == 'true'
        run: echo "::set-output name=result::true"
      - name: Build
        id: build
        if: steps.check_for_build_image.outputs.result == "true"
        run: echo "Run build"
      - name: Remove Build Image Tag
        if: steps.check_for_build_image.outputs.result == "true"
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: "Build Image"
            })
            console.log('Remove "Build Image" label')
