name: Label Filter
on:
  push:
    branches:
      - main
      - master
      - sprint
      - release
    tags:
      - v*
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check For Build Image Label
        id: check_for_build_image
        if: contains(github.event.pull_request.labels.*.name, 'Build Image')
        run: echo "::set-output name=result::true"
      - name: Check For QA Ready Label
        id: check_for_qa_ready
        if: contains(github.event.pull_request.labels.*.name, 'QA Ready')
        run: echo "::set-output name=result::true"
      - name: Buildable
        id: buildable
        if: github.event_name == 'push' || steps.check_for_build_image.outputs.result == 'true' || steps.check_for_build_image.outputs.result == 'true'
        run: echo "::set-output name=result::true"
      - name: Build
        id: build
        if: steps.buildable.outputs.result == 'true'
        run: |
          echo "Run build"
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            COMMIT_SHA=$(cat $GITHUB_EVENT_PATH | jq -r .pull_request.head.sha)
          else
            COMMIT_SHA=$GITHUB_SHA
          fi
          COMMIT_SHA=${COMMIT_SHA::8}
          echo "::set-output name=tag::${COMMIT_SHA::8}"
      - name: "Comment"
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v4
        env:
          DOCKER_TAG: ${{ steps.build.outputs.tag }}
        with:
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: ":computer: Docker image built with tag: `" + process.env.DOCKER_TAG + "`"
            })
      - name: Remove Build Image Tag
        if: steps.check_for_build_image.outputs.result == 'truex'
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: "Build Image"
            })
            console.log('Remove "Build Image" label')
