name: Sync Jira Status Changes

on:
  repository_dispatch:
    types:
      - synchronize_jira

jobs:
  build:
    runs-on: ubuntu-latest
    name: Transition Jira Task From Labels
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GIT_SYNC_TOKEN }}
          script: |
            console.log(context)
            const pageSize = 100
            const updatePullRequestLabels = function(page) {
              github.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "open",
                per_page: pageSize,
                page: page
              }).then(response => {
                response.data.forEach(pullRequest => {
                  if (pullRequest.draft) {
                    return
                  }
                  const hasQAReadyLabel = pullRequest.labels.some(label => {
                    return label.name == "QA Ready"
                  })
                  console.log(pullRequest.number + " hasQAReadyLabel = " + hasQAReadyLabel)
                })
                if (response.data.length >= pageSize) {
                  updatePullRequestLabels(page + 1)
                }
              })
            }
            updatePullRequestLabels(1)
